= DOF Methodology
J. Simmons <jrs@mach30.org>
:revnumber: v0.1
:revdate: 06-05-2018
:revremark: First draft

== First Principles

. OSHW should be developed in a manner like OSS
. The basic building block of OSHW is a component
. Components may be hardware or software
. All components must be built by someone
. Components may be built and acquired from a third party (designated COTS components) or built from source by the developer using them (designated as assemblies)
. COTS components may be open or closed source, as they are built by a third party
. Assembly components must be open source, as they are built by the developer of an open source project
. Software components include firmware and applications (applications may run on or communicate with the OSHW project)
. An OSHW project depends on its Assembly components, but not its COTS components; that is, it must embed the source of Assembly components within its own project structure 
. An OSHW project requires both its Assembly and COTS components 
. Hardware components of an OSHW project are listed in its Bill of Materials (BoM)
. BoMs only define the components of the current project scope; Assembly components have their own independent BoMs 
. OSHW (and OSS) projects must include build instructions as part of their "source"; in other words, a BoM or a collection of files with code is not sufficient to define an open source project

== Derived Assumptions 

. OSHW projects should support fork, branch, merge, and tag operations
. OSHW projects (like modern OSS projects) should be composable at the component level
. OSHW should use "packages" (think npm packages in Nodejs, gems in Ruby, and pipy modules in Python) as the unit of composition for hardware and software components 
. A package should include
.. BoM data
.. Build instructions 
.. Digital design files for this package (e.g. cad files, code files)
.. List of dependencies (hardware and software) - may be implemented in same list as required components, but must be identifiable as dependencies
.. List of required components (hardware and software) - full list of required components can be a computed list by merging dependency list with list of COTS components
. A package should support all activities related to building the project up to and including the item defined in the package.  Examples include
.. Generating a list of BoMs for all Assembly components and the package
.. Generating a purchase list to build the project defined in this package 
.. Generating build instructions for the project defined in this package
. Therefore, every OSHW project is itself a package 
//. There is a subset of data about a component (assemblies and COTS) which needs to be referenced in a variety of places (e.g. BoM, assembly instructions, operating instructions); this data is the component’s ID data and is defined as:
//.. name
//.. url (repository url for assembly components, vendor url for COTS components)
//.. version (* for all or for not relevant?)
//.. description
//. A component is identified by its name, not its part number (part numbers are location dependent, names should be able to identify a part uniquely within a given project scope)
// add material about component common elements, bom elements, and purchasing elements
// add material about computed bom data (part numbers) and how cost data is separate and also computed

== The Methodology 

This methodology covers the process of documenting and sharing OSHW projects, it does not cover the art and science of design.  Clearly, each decision discussed below is the result of the hard work of the developer(s) contributing to the project.

=== Developing Projects

.Starting a Project
. Create directory for new project source
. Initialize a new package for this project in the project directory; package description must include 
.. Project name - used to identify project when included as a dependency and to reference the project in documentation source
.. Project version - used to identify project when included as a dependency and to reference the project in documentation source
.. Project description - short description, used to give human readable name in BoM, instructions, etc
. Create new repository for the project 
. Commit project directory to repository

.Adding a Component to a Project
* If component is hardware and an assembly component
.. If new component, follow steps for *Starting a Project*
.. Add component to dependency list by its ID data
.. Download required source for new component into dependency data (likely a folder)
.. Add component data to BoM (name, quantity, etc)
* If component is hardware and a COTS component
.. Add component to COTS list by its ID data
.. Add component data to BoM (name, quantity, etc)
* If component is software and an assembly component
.. If new component, follow steps for *Starting a Project*
.. Add component to dependency list by its ID data
.. Download required source for new component into dependency data (likely a folder)
* If component is software and a COTS component
.. Add component to COTS list by its ID data

NOTE: Required digital design files should be stored under a _source_ directory in the package they belog to.

TIP: Commit materials to repositories frequently to ensure data is available to other contributors and other projects.

NOTE: Package management tools used with DOF need to include the concept of updating dependencies when new versions are released.

=== Generating BoMs

While BoMs are scoped at the level of the current package, it is helpful to produce a single document containing the collection of BoMs included within the project hierarchy (computed via dependencies).  So, we will first discuss generating the current scope BoM and then the collection of BoMs.

==== Generating BoM for Current Package

.Uses
* BoM data 
* List of required components

TODO

==== Generating Project BoM Collection

.Uses
* Dependency Lists
* BoM data from packages in dependency heirarchy

. Generate a full project dependency list by walking the dependency graph defined by the project’s dependency lists at all levels of the project heirarchy
. Create a new empty document
. Create a new section for each project in the dependency list, and use the project’s BoM data to generate its BoM in this section per above

=== Generating Purchase List

.Uses
* Dependency Lists
* BoM data from packages in dependency heirarch
* List of COTS components (hardware and software) from packages in dependency heirarchy

TODO

=== Generating Build Instructions

.Uses
* List of required components
* Pacakges from dependencies

TODO
