== Introduction

Mach 30 launched https://opendesignengine.net[Open Design Engine] (ODE) in 2012. Since then we have run our own OSHW projects on ODE, observed other groups host OSHW projects on ODE and other sites, and held numerous conversations on and offline about the nature of hosting OSHW projects.  Our conclusion after all these years and experience is the same one we held back in 2012:  the OSHW community is still searching for a project hosting solution that meets the needs of hardware projects (where documentation is part of the source code).

What has changed is our approach to addressing OSHW project hosting.  This time we are starting with the development of a tool independent methodology for developing and sharing OSHW, the Distributed OSHW Framework (DOF).  What do we mean by methodology?  

The Distributed OSHW Framework will be a systematic approach identifying:

* What needs to be shared
* How it should be shared
* The relationships between the various kinds of shared content

Note how developing a methodology is different from identifying best practices, covering case studies, and creating definitions.  A methodology is something one follows; it is a fully defined process.  And by targeting tool independence, we can aim for developing a solution that will stand the test of time, just as version control methods have lasted through cvs, svn, and now git.

=== Methodology Documentation

The methodology is being modeled in a series of YAML files under the `architecture` folder.  A script is then used to generate this readme and the DOF architecture document (located in the `dist` folder).  See the `docs` folder for mataterial on the format of the architecture YAML files.

Please feel free to join the conversation by posting questions/comments as issues in the http://dof.sliderule.io[DOF repository].

=== Related Projects

.Mach 30 Related Projects
* https://opendesignengine.net[Open Design Engine] - legacy OSHW project hosting portal built on https://www.redmine.org/[Redmine]
* http://sliderule.io[Sliderule] - Reference implementation of DOF, being developed in stages
** https://github.com/7BIndustries/sliderule-cli[Sliderule CLI] - Initial component of Sliderule, a command line interface implementation of DOF developed by https://github.com/7BIndustries/[7BIndustries]

.Sources of Inspiration
* http://github.howstr.com/[Howstr] - A project by Matthew Maier to capture how to capture, share, and discover tangible projects

=== Further Reading

* https://www.pearson.com/us/higher-education/product/Gibb-Building-Open-Source-Hardware-DIY-Manufacturing-for-Hackers-and-Makers/9780133373905.html[Building Open Source Hardware: DIY Manufacturing for Hackers and Makers] by Alicia Gibb